title: Never Stand Still
description: Pre-PhD Page
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Sheng Li on GitHub: https://eetose.github.io/

logo: "/assets/images/jedi.png"
favicon_ico: "/assets/images/favicon.ico"


search:
  enabled: true

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap


